config/routes.rb
MoneyTracker::Application.routes.draw do
  root to: 'transactions#index'
  resources :transactions, only: [:index, :edit, :update] do
    collection do
      get :search
    end
  end
  resources :uploads,      only: [:new, :create]
  resources :categories,   only: [] do
    collection do
      get :search
    end
  end
  resources :descriptions, only: [] do
    collection do
      get :search
    end
  end
  resources :locations, only: [] do
    collection do
      get :search
    end
  end
  resources :groupings, only: [] do
    collection do
      get :search
    end
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :transactions

  validates :account_id, presence: true, uniqueness: true

  def name
    self[:name] || self[:account_id]
  end
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :account

  validates :account_id, :source_date, :source_name, :source_amount_in_pence, :source_fit_id, :source_type, :original_description, presence: true
  validates :source_fit_id, uniqueness: true

  before_validation :set_original_description, on: :create

  default_scope { order('COALESCE(date, source_date) DESC, account_id ASC, source_fit_id DESC') }

  class << self
    def search(search_string)
      if (m = /category:(.*)/.match(search_string))
        where(category: m[1])
      elsif (m = /description:(.*)/.match(search_string))
        where(description: m[1])
      elsif (m = /grouping:(.*)/.match(search_string))
        where(grouping: m[1])
      else
        where(
          'source_name ILIKE :q OR source_memo ILIKE :q OR note ILIKE :q OR source_type ILIKE :q OR description ILIKE :q',
          q: "%#{search_string}%"
        )
      end
    end

    def period(period)
      date = Date.from_period(period)
      where(
        'COALESCE(date, source_date) >= ? AND COALESCE(date, source_date) <= ?',
        date.beginning_of_month, date.end_of_month
      )
    end

    def category_search(query)
      unscoped.select('DISTINCT(category)').where('category ILIKE :q', q: "%#{query}%").order('category ASC')
    end

    def description_search(query)
      unscoped.select('DISTINCT(description)').where('description ILIKE :q', q: "%#{query}%").order('description ASC')
    end

    def location_search(description, query)
      unscoped.select('DISTINCT(location)').where('UPPER(description) = UPPER(:description) AND location ILIKE :q', description: description, q: "%#{query}%").order('location ASC')
    end

    def grouping_search(query)
      unscoped.select('DISTINCT(grouping)').where('grouping ILIKE :q', q: "%#{query}%").order('grouping ASC')
    end
  end

  def amount
    source_amount_in_pence / 100.0
  end

  def credit?
    amount > 0
  end

  def debit?
    amount < 0
  end

  def description
    self[:description] || original_description
  end

  def date
    self[:date] || source_date
  end

  private

  def set_original_description
    description = [source_name, source_memo].compact.join(' / ')
    self.original_description = "#{description} (#{source_type})"
  end
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  validates :ofx_file, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate

  private

  def current_period_transactions_path
    transactions_path(period: Time.zone.today.to_s(:period))
  end

  def authenticate
    return true unless Rails.env.production?

    authenticate_or_request_with_http_basic do |user_name, password|
      user_name == USERNAME && password == PASSWORD
    end
  end

  def demo_mode?
    ENV['DEMO_MODE']
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def search
    categories = Category.search(params[:term])
    render json: categories
  end
end

app/controllers/descriptions_controller.rb
class DescriptionsController < ApplicationController
  def search
    descriptions = Description.search(params[:term])
    render json: descriptions
  end
end

app/controllers/groupings_controller.rb
class GroupingsController < ApplicationController
  def search
    groupings = Grouping.search(params[:term])
    render json: groupings
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def search
    locations = Location.search(params[:description], params[:term])
    render json: locations
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    redirect_to current_period_transactions_path unless params[:period]

    @filter = "for #{Date.from_period(params[:period]).to_s(:month_and_year)}"
    @date_format = :weekday_and_day
    @transactions = Transaction.period(params[:period])
    render :bulk_edit if params[:edit].present?
  end

  def edit
    @transaction = Transaction.find(params[:id])
  end

  def update
    transaction = Transaction.find(params[:id])
    transaction.update_attributes(params[:transaction].permit(:date, :description, :location, :note, :category, :grouping))
    if request.xhr?
      render text: 'OK'
    else
      redirect_to :back
    end
  end

  def search
    @filter =  "matching '#{params[:q]}'"
    @date_format = :human_friendly
    @transactions = Transaction.search(params[:q])
    if params[:edit].present?
      render :bulk_edit
    else
      render :index
    end
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :hide_uploads_in_demo_mode

  def new
    @upload = Upload.new
  end

  def create
    upload_params = params[:upload] ? params[:upload].permit(:ofx_file) : {}
    @upload = Upload.new(upload_params)
    if @upload.valid?
      imported, duplicates = StatementImporter.import(upload_params[:ofx_file])
      flash[:info] = "#{imported} transactions were imported.  #{duplicates} duplicate transactions were ignored."
      redirect_to current_period_transactions_path
    else
      flash.now[:info] = 'Please select the OFX file to upload'
      render :new
    end
  end

  private

  def hide_uploads_in_demo_mode
    render :demo if demo_mode?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_previous_period(period, path_options = {})
    previous_period = Date.from_period(period) - 1.month
    link_to transactions_path({ period: previous_period.to_s(:period) }.merge(path_options)), class: 'previous_period' do
      ['<i class="glyphicon glyphicon-chevron-left"></i>', previous_period.to_s(:month_and_year)].join(' ').html_safe
    end
  end

  def link_to_next_period(period, path_options = {})
    next_period = Date.from_period(period) + 1.month
    link_to transactions_path({ period: next_period.to_s(:period) }.merge(path_options)), class: 'next_period' do
      [next_period.to_s(:month_and_year), '<i class="glyphicon glyphicon-chevron-right"></i>'].join(' ').html_safe
    end
  end

  def link_to_location(transaction)
    return if transaction.location.blank?
    query = CGI.escape(transaction.location)
    link_to "https://maps.google.co.uk/maps?q=#{query}", target: 'blank', title: 'View in Google Maps' do
      '<i class="glyphicon glyphicon-map-marker"></i>'.html_safe
    end
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def transaction_description(transaction)
    transaction.description
  end

  def income(amount)
    number_to_currency(amount, :unit => '£')
  end

  def expense(amount)
    number_to_currency(-amount, :unit => '£')
  end

  def transaction_amount_in(transaction)
    income(transaction.amount) if transaction.credit?
  end

  def transaction_amount_out(transaction)
    expense(transaction.amount) if transaction.debit?
  end

  def transaction_income(transactions)
    income = transactions.select(&:credit?).sum(&:amount)
    number_to_currency(income, unit: '£')
  end

  def transaction_expenditure(transactions)
    expenditure = transactions.select(&:debit?).sum(&:amount)
    number_to_currency(-expenditure, unit: '£')
  end
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{charset: 'utf-8'}
    %meta{'http-equiv' => 'X-UA-Compatible', content: 'IE=edge'}
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1'}
    %title= ['MoneyTracker', yield(:title)].compact.join(' - ')
    = csrf_meta_tag
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"

  %body
    .container-fluid
      .navbar.navbar-default
        = link_to 'Money Tracker', root_path, class: 'navbar-brand'
        %ul.nav.navbar-nav
          %li
            = link_to 'Recent transactions', transactions_path
          %li
            = link_to 'Upload statement', new_upload_path
        %div
          = form_tag search_transactions_path, method: :get, class: 'navbar-form pull-right' do
            .form-group
              = text_field_tag :q, params[:q], size: '60', placeholder: 'Search transactions', class: 'search-query form-control'
              = submit_tag 'Search', class: 'btn btn-default'
      -if flash[:info]
        #flash.alert.alert-info= flash[:info]

      = yield

app/views/transactions/_table_body.html.haml
%tbody
  - @transactions.each_with_index do |transaction, index|
    = content_tag_for(:tr, transaction) do
      %td
        - klass = 'firstOfDay' if index == 0 || transaction.date != @transactions[index-1].date
        %span.date{class: klass}= transaction.date.to_s(date_format)
      %td.account= transaction.account.name
      %td.detail
        %p.description_and_category
          = link_to transaction_description(transaction), search_transactions_path(q: ['description', transaction_description(transaction)].join(':')), class: 'description'
          = link_to_location(transaction)
          - unless transaction.category.blank?
            = link_to transaction.category, search_transactions_path(q: ['category', transaction.category].join(':')), class: 'category label label-info'
          - unless transaction.grouping.blank?
            = link_to transaction.grouping, search_transactions_path(q: ['grouping', transaction.grouping].join(':')), class: 'grouping label label-info'
        = simple_format(transaction.note, class: 'note')
      %td.paid_in= transaction_amount_in(transaction)
      %td.paid_out= transaction_amount_out(transaction)
      %td.actions= link_to 'Edit', edit_transaction_path(transaction)

app/views/transactions/_table_footer.html.haml
%tfoot
  %tr
    %td{colspan: 3}
    %td#income.paid_in= transaction_income(@transactions)
    %td#expenditure.paid_out= transaction_expenditure(@transactions)
    %td

app/views/transactions/_table_header.html.haml
%thead
  %tr
    %th.date Date
    %th.account Account
    %th.detail Detail
    %th.paid_in Paid in
    %th.paid_out Paid out
    %th.actions Actions

app/views/transactions/bulk_edit.html.haml
- page_title = "Edit transactions #{@filter}"

- content_for :title do
  = page_title

.row
  .col-md-8
    %h1= page_title
  .col-md-4
    = link_to 'View transactions', url_for(params.merge(edit: '')), class: 'btn btn-default pull-right'

- if params[:period]
  %nav
    %ul.pager
      %li.previous= link_to_previous_period params[:period], edit: true
      %li.next= link_to_next_period params[:period], edit: true

%table#transactions.table.table-striped.table-condensed.table-bordered
  %thead
    %tr
      %th Date
      %th Account
      %th Description
      %th Location
      %th Paid in
      %th Paid out
      %th Note
      %th Category
      %th Group
  %tbody
    - @transactions.each do |transaction|
      = content_tag_for(:tr, transaction) do
        %td
          = form_for(transaction, html: {id: nil}) do |transaction_form|
            = transaction_form.text_field :date, size: '10', id: nil, value: transaction.date
            %span.help-block
              Original:
              %span.text-info.source_date= transaction.source_date
            = transaction_form.submit 'Save date', id: nil
        %td
          %span.text-info.account_name= transaction.account.name
        %td
          = form_for(transaction, html: {id: nil}) do |transaction_form|
            = transaction_form.text_field :description, size: '80', id: nil, value: transaction.description, class: 'description'
            %span.help-block
              Original:
              %span.text-info.original_description= transaction.original_description
            = transaction_form.submit 'Save description', id: nil
        %td
          = form_for(transaction, html: {id: nil}) do |transaction_form|
            = transaction_form.text_field :location, size: '40', id: nil, value: transaction.location, class: 'location'
            = transaction_form.submit 'Save location', id: nil
        %td= transaction_amount_in(transaction)
        %td= transaction_amount_out(transaction)
        %td
          = form_for(transaction, html: {id: nil}) do |transaction_form|
            = transaction_form.text_area :note, size: '40x3', id: nil
            = transaction_form.submit 'Save note', id: nil
        %td
          = form_for(transaction, html: {id: nil}) do |transaction_form|
            = transaction_form.text_field :category, size: 40, id: nil, class: 'category'
            = transaction_form.submit 'Save category', id: nil
        %td
          = form_for(transaction, html: {id: nil}) do |transaction_form|
            = transaction_form.text_field :grouping, size: 40, id: nil, class: 'grouping'
            = transaction_form.submit 'Save grouping', id: nil

app/views/transactions/edit.html.haml
- page_title = "Edit transaction"

- content_for :title do
  = page_title

%h1= page_title

= form_for @transaction, html: {class: 'edit_transaction transaction form-horizontal'} do |transaction_form|
  .form-group
    %label.col-sm-1.control-label Account
    .col-sm-6
      %p.form-control-static.account_name= @transaction.account.name
  .form-group
    = transaction_form.label :date, class: 'control-label col-sm-1'
    .col-sm-6
      = transaction_form.text_field :date, size: '10', value: @transaction.date, class: 'form-control'
      %span.help-block
        Original:
        %span.text-info.source_date= @transaction.source_date
  .form-group
    = transaction_form.label :description, class: 'control-label col-sm-1'
    .col-sm-6
      = transaction_form.text_field :description, size: '80', value: @transaction.description, class: 'description form-control'
      %span.help-block
        Original:
        %span.text-info.original_description= @transaction.original_description
  .form-group
    = transaction_form.label :location, class: 'control-label col-sm-1'
    .col-sm-6
      = transaction_form.text_field :location, size: '40', value: @transaction.location, class: 'location form-control'
  .form-group
    = transaction_form.label :note, class: 'control-label col-sm-1'
    .col-sm-6
      = transaction_form.text_area :note, size: '40x3', class: 'form-control'
  .form-group
    = transaction_form.label :category, class: 'control-label col-sm-1'
    .col-sm-6
      = transaction_form.text_field :category, size: 40, class: 'category form-control'
  .form-group
    = transaction_form.label :grouping, class: 'control-label col-sm-1'
    .col-sm-6
      = transaction_form.text_field :grouping, size: 40, class: 'grouping form-control'
  .form-group
    .col-sm-offset-1.col-sm-6
      = transaction_form.submit 'Save', class: 'btn btn-default'

app/views/transactions/index.html.haml
- page_title = "Transactions #{@filter}"

- content_for :title do
  = page_title

.row
  .col-md-8
    %h1= page_title
  .col-md-4
    = link_to url_for(params.merge(edit: true)), class: 'btn btn-default pull-right' do
      - ['<i class="glyphicon glyphicon-edit"></i>', 'Edit transactions'].join(' ').html_safe

- if params[:period]
  %nav
    %ul.pager
      %li.previous= link_to_previous_period params[:period], unexplained: true
      %li.next= link_to_next_period params[:period], unexplained: true

%table#transactions.table.table-striped.table-condensed.table-bordered
  = render partial: 'table_header'
  = render partial: 'table_footer'
  = render partial: 'table_body', locals: {date_format: @date_format}

app/views/transactions/monthly.html.haml
- page_title = "Monthly overview"

- content_for :title do
  = page_title

%h1= page_title

app/views/transactions/overview.html.haml
%h1 Overview

%h2 Date of the earliest transaction
%p= Transaction.earliest_transaction.date.to_s(:human_friendly)

%h2 Total income
%p= income Transaction.total_income

%h2 Total expense
%p= expense Transaction.total_expense

%h2 Average daily income
%p= income Transaction.average_daily_income

%h2 Average daily expense
%p= expense Transaction.average_daily_expense

app/views/uploads/demo.html.haml
- page_title = "Upload statement - Disabled"

- content_for :title do
  = page_title

%h1= page_title

%p Uploads have been disabled in the demo

app/views/uploads/new.html.haml
- page_title = "Upload statement"

- content_for :title do
  = page_title

%h1= page_title

= form_for @upload, html: {multipart: true} do |upload_form|
  .form-group
    = upload_form.label      :ofx_file
    = upload_form.file_field :ofx_file
  .form-group
    = upload_form.submit    'Upload', class: 'btn btn-default'